data_loader:
  name: "CIFAR10"
  corruption:
    rotation:
      degrees: [19.999, 20.001]
      resample: 3
            #    color_jitter:
            #      brightness: [0.49, 0.51]
device: "cuda:3"
batch_size: 128
tnet:
  transform_list: ["rotation"]
  path: "tnet_models/rot_20/checkpoint_10.tar"
pretrained_model:
  path: "pretrained_models/cifar_resize_randomcrop/checkpoint_17.tar"

