data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 0.50
    contrast_var: 0.05
    mode: "train"
save_dir: "pretrained_models/cifar_c_050_dist"
save_as: "runs/cifar_c_050_dist"
device: "cuda:3"
batch_size: 32
