data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 1.00
    contrast_var: 0.1
    mode: "train"
save_dir: "pretrained_models/cifar_c_100_dist"
save_as: "runs/cifar_c_100_dist"
device: "cuda:0"
batch_size: 32
