data_loader:
  name: "CIFAR10"
  corruption:
     color_jitter:
         hue: [-0.151, 0.149]
device: "cuda:0"
batch_size: 128
tnet:
  save_as: "runs/hue_-15"
  save_dir: "tnet_models/hue_-15/"
  transform_list: ["hue"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_2/checkpoint_17.tar"

