data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 1.75
    contrast_var: 0.05
device: "cuda:3"
batch_size: 128
tnet:
  name: "vec"
  transform_list: ["contrast"]
  path: "tnet_models/c_175_dist/checkpoint_10.tar"
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"
oracle_model:
  path: "pretrained_models/cifar_c_175_dist/checkpoint_40.tar"
