data_loader:
  name: "MNIST"
  corruption:
    degrees: 30
device: "cuda:0"
batch_size: 128
tnet:
  name: "vec"
  save_as: "runs/rot_30"
  save_dir: "tnet_models/rot_30"
  transform_list: ["rotation"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/mnist_normalize/checkpoint_10.tar"

