data_loader:
  name: "MNIST"
  corruption:
    degrees: -100.
device: "cuda:0"
batch_size: 128
tnet:
  name: "vec"
  save_as: "runs/rot_-100"
  save_dir: "tnet_models/rot_-100"
  transform_list: ["rotation"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/mnist_normalize/checkpoint_10.tar"

