data_loader:
  name: "CIFAR10"
  corruption:
    degrees: 25.
device: "cuda:0"
batch_size: 128
tnet:
  save_as: "runs/rot_25"
  save_dir: "tnet_models/rot_25"
  transform_list: ["rotation"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_resize_randomcrop/checkpoint_17.tar"

