data_loader:
  name: "MNIST"
  corruption:
    degrees: 100
device: "cuda:0"
tnet:
  name: "vec"
  save_as: "runs/rot_100"
  save_dir: "tnet_models/rot_100"
  transform_list: ["rotation"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/mnist_normalize/checkpoint_10.tar"

