data_loader:
  name: "CIFAR10"
  corruption:
    rotation:
      degrees: [-15.001, -14.999]
      resample: 3
device: "cuda:0"
batch_size: 128
tnet:
  save_as: "runs/rot_-15"
  save_dir: "tnet_models/rot_-15"
  transform_list: ["rotation"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_resize_randomcrop/checkpoint_17.tar"

