data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 0.75
    brightness_var: 0.05
device: "cuda:3"
batch_size: 128
tnet:
  name: "cnn"
  transform_list: ["brightness"]
  path: "tnet_models/br_075_dist/checkpoint_60.tar"
pretrained_model:
  path: "pretrained_models/cifar_resize_randomcrop/checkpoint_17.tar"

