data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 0.250
    brightness_var: 0.05
device: "cuda:3"
batch_size: 128
tnet:
  name: "cnn"
  transform_list: ["brightness"]
  path: "tnet_models/br_025_dist/checkpoint_60.tar"
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

