data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 0.250
    brightness: 1.0
device: "cuda:0"
batch_size: 128
tnet:
  name: "vec"
  epochs: 80
  save_as: "runs/t_10/c_025_br_100"
  save_dir: "tnet_models/t_10/c_025_br_100/"
  transform_list: ["contrast", "brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

