data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 0.75
    contrast_var: 0.05
    brightness: 1.0
    brightness_var: 0.05
device: "cuda:0"
batch_size: 128
tnet:
  epochs: 60
  name: "cnn"
  save_as: "runs/c_075_br_100"
  save_dir: "tnet_models/c_075_br_100/"
  transform_list: ["contrast", "brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

