data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 1.50
    brightness: 0.50
device: "cuda:0"
batch_size: 128
tnet:
  name: "vec"
  save_as: "runs/c_150_br_050"
  save_dir: "tnet_models/c_150_br_050/"
  transform_list: ["contrast", "brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_2/checkpoint_17.tar"

