data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 1.50
    brightness: 1.0
device: "cuda:0"
batch_size: 128
tnet:
  epochs: 80
  name: "vec"
  save_as: "runs/c_150_br_100"
  save_dir: "tnet_models/c_150_br_100/"
  transform_list: ["contrast", "brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

