data_loader:
  name: "MNIST"
  corruption:
    degrees: -10.
    degrees_var: 2.
device: "cuda:0"
batch_size: 128
tnet:
  name: "cnn"
  save_as: "runs/rot_-10_dist"
  save_dir: "tnet_models/rot_-10_dist"
  transform_list: ["rotation"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/mnist_normalize/checkpoint_10.tar"

