data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 0.50
    contrast_var: 0.05
    brightness: 1.25
    brightness_var: 0.05
device: "cuda:0"
batch_size: 128
tnet:
  epochs: 60
  name: "cnn"
  save_as: "runs/br_125_c_050"
  save_dir: "tnet_models/br_125_c_050/"
  transform_list: ["contrast", "brightness", "rotation"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

