data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 0.75
device: "cuda:0"
batch_size: 128
tnet:
  name: "vec"
  save_as: "runs/br_075"
  save_dir: "tnet_models/br_075/"
  transform_list: ["brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_2/checkpoint_17.tar"

