data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 1.75
device: "cuda:0"
batch_size: 128
tnet:
  name: "vec"
  save_as: "runs/br_175"
  save_dir: "tnet_models/br_175/"
  transform_list: ["brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"
oracle_model:
  path: "pretrained_models/cifar_br_175/checkpoint_40.tar"

