data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 1.50
device: "cuda:0"
batch_size: 128
tnet:
  save_as: "runs/br_150"
  save_dir: "tnet_models/br_150/"
  transform_list: ["brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_2/checkpoint_17.tar"

