data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 1.25
device: "cuda:0"
batch_size: 128
tnet:
  name: "vec"
  save_as: "runs/br_125"
  save_dir: "tnet_models/br_125/"
  transform_list: ["brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

