data_loader:
  name: "MNIST"
  corruption:
    degrees: 75
    degrees_var: 2
  n_examples: 100
pretrained_model: 
    path: "pretrained_models/mnist_normalize/checkpoint_10.tar"
save_dir: "tl_models/rot_75_dist/n_100"
save_as: "runs/tl_rot_75_dist/n_100"
device: "cuda:3"
batch_size: 32
