data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 0.5
device: "cuda:0"
batch_size: 128
tnet:
  name: "vec"
  save_as: "runs/c_050"
  save_dir: "tnet_models/c_050/"
  transform_list: ["contrast"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

