data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 1.50
device: "cuda:0"
batch_size: 128
tnet:
  name: "vec"
  save_as: "runs/c_150"
  save_dir: "tnet_models/c_150/"
  transform_list: ["contrast"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_2/checkpoint_17.tar"

