data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 0.25
    brightness_var: 0.05
    brightness: 0.50
    contrast_var: 0.05
    mode: "train"
save_dir: "pretrained_models/cifar_c_025_br_050_dist"
save_as: "runs/cifar_c_025_br_050_dist"
device: "cuda:2"
batch_size: 32
