data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 0.50
    brightness_var: 0.05
    contrast: 1.75
    contrast_var: 0.05
    mode: "train"
save_dir: "pretrained_models/cifar_c_175_br_050_dist"
save_as: "runs/cifar_c_175_br_050_dist"
device: "cuda:2"
batch_size: 32
