data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 1.75
device: "cuda:3"
batch_size: 128
tnet:
  name: "vec"
  transform_list: ["brightness"]
  path: "tnet_models/br_175/checkpoint_60.tar"
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"
oracle_model:
  path: "pretrained_models/cifar_br_175/checkpoint_40.tar"

