data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 0.50
    brightness_var: 0.05
device: "cuda:2"
batch_size: 128
tnet:
  name: "cnn"
  save_as: "runs/br_050_dist"
  save_dir: "tnet_models/br_050_dist/"
  transform_list: ["brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

