data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 0.25
    brightness_var: 0.1
device: "cuda:0"
batch_size: 128
tnet:
  save_as: "runs/br_025_dist"
  save_dir: "tnet_models/br_025_dist/"
  transform_list: ["brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_resize_randomcrop/checkpoint_17.tar"

