data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 1.50
    brightness_var: 0.05
device: "cuda:2"
batch_size: 128
tnet:
  name: "cnn"
  save_as: "runs/br_150_dist"
  save_dir: "tnet_models/br_150_dist/"
  transform_list: ["contrast", "brightness", "rotation"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

