data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 1.25
    brightness_var: 0.1
device: "cuda:0"
batch_size: 128
tnet:
  name: "cnn"
  save_as: "runs/br_125_dist"
  save_dir: "tnet_models/br_125_dist/"
  transform_list: ["brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar_2/checkpoint_17.tar"

