data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 1.
device: "cuda:3"
batch_size: 128
tnet:
  name: "cnn"
  transform_list: ["contrast"]
  path: "tnet_models/c_100_dist/checkpoint_10.tar"
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

