data_loader:
  name: "MNIST"
  corruption:
      degrees: 30.
      degrees_var: 5
device: "cuda:3"
batch_size: 128
tnet:
  name: "cnn"
  transform_list: ["contrast", "brightness", "rotation"]
  path: "tnet_models/rot_30_5_dist/checkpoint_30.tar"
pretrained_model:
  path: "pretrained_models/mnist_normalize/checkpoint_10.tar"
oracle_model:
  path: "pretrained_models/mnist_rot_30_5_dist/checkpoint_10.tar"

