data_loader:
  name: "MNIST"
  corruption:
    degrees: 30.
    degrees_var: 25.
device: "cuda:3"
batch_size: 128
tnet:
  name: "cnn"
  transform_list: ["rotation"]
  path: "tnet_models/rot_30_25_dist/checkpoint_10.tar"
pretrained_model:
  path: "pretrained_models/mnist_normalize/checkpoint_10.tar"
oracle_model:
  path: "pretrained_models/mnist_rot_30_25_dist/checkpoint_10.tar"

