data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 0.75
    brightness: 0.50
device: "cuda:3"
batch_size: 128
tnet:
  name: "vec"
  transform_list: ["contrast", "brightness"]
  path: "tnet_models/c_075_br_050/checkpoint_57.tar"
pretrained_model:
  path: "pretrained_models/cifar_resize_randomcrop/checkpoint_17.tar"

