data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 1.75
    contrast_var: 0.05
    brightness: 1.00
    brightness_var: 0.05
device: "cuda:3"
batch_size: 128
tnet:
  name: "cnn"
  transform_list: ["contrast", "brightness"]
  path: "tnet_models/c_175_br_100/checkpoint_60.tar"
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

