data_loader:
  name: "CIFAR10"
  corruption:
    contrast: 1.50
device: "cuda:3"
batch_size: 128
tnet:
  name: "vec"
  transform_list: ["contrast"]
  path: "tnet_models/c_150/checkpoint_60.tar"
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"

