data_loader:
  name: "CIFAR10"
  input_size: [3, 32, 32]
  corruption:
    color_jitter:
      brightness: [0.49, 0.51]
device: "cuda:0"
tnet:
  save_dir: "tnet_models/demo"
  transform_list: ["brightness"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/cifar/checkpoint_19.tar"

