data_loader:
  name: "CIFAR10"
  input_size: [3, 32, 32]
  corruption:
    color_jitter:
      saturation: [1.249, 1.251]
device: "cuda:1"
tnet:
  save_dir: "tnet_models/demo"
  transform_list: ["saturation"]
  batch_size: 128
pretrained_model:
  path: "pretrained_models/checkpoint_24.tar"

