data_loader:
  name: "CIFAR10"
  corruption:
    rotation:
      degrees: [-5.001, -5.002]
      resample: 3
            #    color_jitter:
            #      brightness: [0.49, 0.51]
device: "cuda:3"
batch_size: 128
tnet:
  transform_list: ["rotation"]
  path: "tnet_models/demo/checkpoint_16.tar"
pretrained_model:
  path: "pretrained_models/cifar_2/checkpoint_17.tar"

