data_loader:
  name: "MNIST"
  corruption:
    degrees: 30
    degrees_var: 2
  n_examples: 5000
pretrained_model: 
    path: "pretrained_models/mnist_normalize/checkpoint_10.tar"
save_dir: "tl_models/rot_30_dist/n_5000"
save_as: "runs/tl_rot_30_dist/n_5000"
device: "cuda:3"
batch_size: 32
