data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 0.25
    brightness_var: 0.05
device: "cuda:3"
batch_size: 128
tnet:
  name: "vec"
  transform_list: ["brightness"]
  path: "tnet_models/br_025_dist/checkpoint_10.tar"
pretrained_model:
  path: "pretrained_models/cifar_normalize/checkpoint_40.tar"
oracle_model:
  path: "pretrained_models/cifar_br_025_dist/checkpoint_40.tar"


