data_loader:
  name: "MNIST"
  corruption:
      degrees: -10.
      degrees_var: 2
device: "cuda:3"
batch_size: 128
tnet:
  transform_list: ["rotation"]
  path: "tnet_models/rot_-10_dist/checkpoint_10.tar"
pretrained_model:
  path: "pretrained_models/mnist_normalize/checkpoint_20.tar"
oracle_model:
  path: "pretrained_models/mnist_rot_-10_dist/checkpoint_40.tar"

