data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 0.75
    brightness_var: 0.05
    mode: "train"
save_dir: "pretrained_models/cifar_br_075_dist"
save_as: "runs/cifar_br_075_dist"
device: "cuda:0"
batch_size: 32
