data_loader:
  name: "CIFAR10"
  corruption:
    brightness: 0.25
  n_examples: 7000
pretrained_model: 
    path: "pretrained_models/cifar_normalize/checkpoint_40.tar"
save_dir: "tl_models/br_025/n_7000"
save_as: "runs/tl_br_025/n_7000"
device: "cuda:3"
batch_size: 32
